### ISSUE TITLE
Pass order number to cells

### ISSUE THREAD

**Issue by DaveyEdwards** [FormidableLabs/radium-grid#15]
Ability to give order numbers to cells for more dynamic content

**Comment by braposo** [comment]
@DaveyEdwards saw your issue after creating mine (https://github.com/FormidableLabs/radium-grid/issues/22) and you can actually use `order` for each `Cell` component (https://github.com/FormidableLabs/radium-grid/blob/master/src/components/cell.js#L36). 

If you meant changing the order on different breakpoints, I've submitted a PR about that (https://github.com/FormidableLabs/radium-grid/pull/23) so let's hope it's merged soon!

**Comment by DaveyEdwards** [comment]
@braposo sweet! And no I was just wanted to be able to pass a order number in to start.  The different breakpoints wasn't even on my mind yet, but I am excited for it now thanks!

**Comment by tptee** [comment]
Custom orders per breakpoint are now supported in v1.1.0!
https://github.com/FormidableLabs/radium-grid/releases/tag/v1.1.0
