### ISSUE TITLE
Leveraging Grid's breakpoints using window.matchMedia(..)

### ISSUE THREAD

**Issue by choonchernlim** [FormidableLabs/radium-grid#38]
This is due to my unfamiliarity with `radium` and media queries in general, but I'm trying to figure out how to leverage `Grid`'s breakpoints using `window.matchMedia(..)` properly.

To further illustrate, here's a problem set... I want build a React component that wraps `material-ui`'s [LeftNav](http://www.material-ui.com/#/components/left-nav). The goal is if the Grid falls into `large` or `xlarge` category, I want the LeftNav to be shown. Otherwise, collapse it. 

Ideally, I would like to reuse the `radium-grid`'s default breakpoint values, if possible, instead of hardcoding the width. 

So, my code looks something like this:-

	// line in question... currently hardcoding max-width value from `Grid.defaultProps.breakpoints.medium`
	const mediumGridMaxWidth = 1024;

	const mql = window.matchMedia(`(min-width: ${mediumGridMaxWidth + 1}px)`);

	export default class extends React.Component {
	  constructor(props) {
	    super(props);
	    this.state = { open: true, mql };
	  }

	  componentWillMount() {
	    this.state.mql.addListener(this.handleMediaQueryChanged);
	    this.handleMediaQueryChanged();
	  }

	  componentWillUnmount() {
	    this.state.mql.removeListener(this.handleMediaQueryChanged);
	  }

	  handleMediaQueryChanged = () => this.setState({ open: this.state.mql.matches });

	  render() {
	    return (
	      <LeftNav open={this.state.open} containerStyle={style.leftNav}>
	        <MenuItem href="/">Home</MenuItem>
	        <MenuItem href="/chuck-norris">Chuck Norris</MenuItem>
	      </LeftNav>
	    );
	  }
	}
	
One way to get the breakpoint value, I can do rudimentary regexp... but it seems pretty hacky:-

	// returns 1024
	const mediumGridMaxWidth = parseInt(Grid.defaultProps.breakpoints.medium.match(/max-width: (\d+)px/)[1], 10);

Another way is to leverage `css-mediaquery` to do the same thing:-

	import cssMediaQuery from 'css-mediaquery';

	// returns 1024
	const mediumGridMaxWidth = parseInt(cssMediaQuery
	  .parse(Grid.defaultProps.breakpoints.medium)[0]
	  .expressions.find(e => e.modifier === 'max' && e.feature === 'width').value, 10);

My question is... is there a better approach to apply `radium-grid`'s breakpoints using `window.matchMedia(..)`?

Thank you.

**Comment by tptee** [comment]
Radium uses `matchMedia` internally, so you don't have to setup any listeners. Just use the media query strings as inline styles like so:

```es6
const styles = {
  color: '#000',
  [Grid.defaultProps.breakpoints.medium]: {
    color: '#fff'
  }
}

Radium will take it from there :)

**Comment by choonchernlim** [comment]
But how do I use `Grid.defaultProps.breakpoints.medium` to trigger a state change of my component so that I can pass the new state to `LeftNav`'s `open` property to either open/close the left navigation? Thanks.

**Comment by tptee** [comment]
You could just cut off the `@media` portion of the `Grid.defaultProps.breakpoints.medium` string and pass that to `window.matchMedia`, which should then work the way you previously set it up.

I'm afraid exposing anything besides the strings of the default media queries is outside the scope of `radium-grid`'s API.
