### ISSUE TITLE
How to center align a Cell inside a Grid?

### ISSUE THREAD

**Issue by 123ndy** [FormidableLabs/radium-grid#47]
How can a Cell be placed in the middle of a grid?

For example; if I have a Cell with `width='1/2'`, how can that Cell be placed inside the Grid so it have `1/4` of space on each side (without making extra Cells just to fill the empty space)?

**Comment by tptee** [comment]
Duplicate of #42, but watch that issue–I'll be posting updates there as I implement a solution!
